In [1]:
!pip install pandas numpy openpyxl sqlalchemy pymysql

Requirement already satisfied: pandas in c:\users\wakaas\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy in c:\users\wakaas\anaconda3\lib\site-packages (2.3.5)
Requirement already satisfied: openpyxl in c:\users\wakaas\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: sqlalchemy in c:\users\wakaas\anaconda3\lib\site-packages (2.0.43)
Collecting pymysql
  Downloading pymysql-1.2.3-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\wakaas\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\wakaas\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\wakaas\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: et-xmlfile in c:\users\wakaas\anaconda3\lib\site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: greenlet>=1 in c:\users\wakaas\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\wakaas\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: six>=1.5 in c:\users\wakaas\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pymysql-1.2.3-py3-none-any.whl (46 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.3

In [2]:
# Importing Libraries

import pandas as pd
import numpy as np

In [5]:
# Laod the data

df = pd.read_excel('Ecommerce_Unclean_Project.xlsx')

In [6]:
# Explore the dataset

df.head()

,Order_ID,Order_Date,Customer_Name,Email,Phone,City,State,Product,Category,Qty,Unit_Price,Discount,Payment_Mode,Order_Status,Delivery_Date
0,ORD1002,30-06-2025,Neha,neha82@gmail.com,9.829008e+09,Delhi,Delhi,Chair,Furniture,4.0,1999.0,NaN,UPI,Pending,03-07-2025
1,ORD1003,03-02-2025,Rohit,rohit45@gmail.com,9.280491e+09,Pune,Maharashtra,Watch,Fashion,5.0,4999.0,20,Card,Pending,09-02-2025
2,ORD1004,06-05-2025,Amit,amit6@gmail.com,9.943311e+09,Jaipur,Rajasthan,Mouse,Electronics,3.0,1999.0,5,COD,Returned,08-05-2025
3,ORD1005,20-01-2025,Vikas,vikas51@gmail.com,9.495120e+09,Bengaluru,Karnataka,Laptop,Electronics,NaN,NaN,15,Wallet,Pending,27-01-2025
4,ORD1006,02-04-2025,Rohit,rohit71@gmail.com,9.237332e+09,Pune,Maharashtra,Bottle,Home,NaN,1999.0,,Wallet,Cancelled,07-04-2025

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 524 entries, 0 to 523
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       524 non-null    object
 1   Order_Date     524 non-null    object
 2   Customer_Name  524 non-null    object
 3   Email          524 non-null    object
 4   Phone          502 non-null    float64
 5   City           524 non-null    object
 6   State          524 non-null    object
 7   Product        524 non-null    object
 8   Category       524 non-null    object
 9   Qty            457 non-null    float64
 10  Unit_Price     471 non-null    float64
 11  Discount       455 non-null    object
 12  Payment_Mode   524 non-null    object
 13  Order_Status   524 non-null    object
 14  Delivery_Date  503 non-null    object
dtypes: float64(3), object(12)
memory usage: 61.5+ KB

In [8]:
# Statistical Summary

df.describe()

              Phone         Qty   Unit_Price
count  5.020000e+02  457.000000   471.000000
mean   9.544725e+09    2.800875  3168.639066
std    2.636920e+08    1.963974  2969.682209
min    9.104441e+09   -1.000000   499.000000
25%    9.315673e+09    1.000000   999.000000
50%    9.533562e+09    3.000000  1999.000000
75%    9.792574e+09    5.000000  4999.000000
max    9.999074e+09    5.000000  9999.000000

In [9]:
# Data Shape

df.shape

(524, 15)

In [10]:
# Missing Values
df.isnull().sum()

Order_ID          0
Order_Date        0
Customer_Name     0
Email             0
Phone            22
City              0
State             0
Product           0
Category          0
Qty              67
Unit_Price       53
Discount         69
Payment_Mode      0
Order_Status      0
Delivery_Date    21
dtype: int64

In [13]:
# Duplicate Records
df.duplicated().sum()

np.int64(0)

In [12]:
# Remove duplicates

df.drop_duplicates(inplace=True)

In [17]:
# Replace Invalid 
df.replace(['N/A','NULL',''],np.nan,inplace=True)

In [22]:
# Remove EXtra Spaces

df=df.apply(lambda x:x.str.strip()if x.dtype=='object' else x)

In [24]:
# Standardize Text Format

df['Customer_Name']=df['Customer_Name'].str.title()
df['City']=df['City'].str.title()
df['State']=df['State'].str.title()

In [28]:
# Validate Email ID

df=df[df['Email'].str.contains('@',na=False)]

In [29]:
# Convert Date Columns

df['Order_Date']=pd.to_datetime(df['Order_Date'],errors='coerce')
df['Delivery_Date']=pd.to_datetime(df['Delivery_Date'],errors='coerce')

In [31]:
# Convert Numeric Values

cols=['Qty','Unit_Price','Discount']
for c in cols:
    df[c]=pd.to_numeric(df[c],errors='coerce')

In [32]:
# Remove Invalid Quantity

df=df[df['Qty']>0]

In [34]:
# Fill Missing Values

df['Discount'].fillna(0)
df['Phone'].fillna('Unknown')
df['Delivery_Date'].fillna(df['Order_Date'])

0     2025-03-07
1     2025-09-02
2     2025-08-05
5     2025-02-10
6     2025-02-17
         ...
519   2025-02-17
520          NaT
521   2025-04-10
522   2025-01-11
523   2025-09-03
Name: Delivery_Date, Length: 380, dtype: datetime64[ns]

In [35]:
# Feature Engineering
# 1.Total Sales
df['Sales']=df['Qty']*df['Unit_Price']

In [37]:
# 2.Net Amount

df['Net_Amount']=df['Sales']-(df['Sales']*df['Discount']/100)

In [39]:
# 3.Profit (Example: 20%)

df['Profit']=df['Net_Amount']*0.20

In [42]:
# 4.Order Month

df['Month']=df['Order_Date'].dt.month_name()

In [45]:
# 5.Order Year
df['Year']=df['Order_Date'].dt.year

In [46]:
# 6. Weekday

df['Weekday']=df['Order_Date'].dt.day_name()

In [48]:
# Final Data Validation

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 380 entries, 0 to 523
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       380 non-null    object
 1   Order_Date     333 non-null    datetime64[ns]
 2   Customer_Name  380 non-null    object
 3   Email          380 non-null    object
 4   Phone          380 non-null    object
 5   City           380 non-null    object
 6   State          380 non-null    object
 7   Product        380 non-null    object
 8   Category       380 non-null    object
 9   Qty            380 non-null    float64
 10  Unit_Price     343 non-null    float64
 11  Discount       380 non-null    float64
 12  Payment_Mode   380 non-null    object
 13  Order_Status   380 non-null    object
 14  Delivery_Date  135 non-null    datetime64[ns]
 15  Sales          343 non-null    float64
 16  Net_Amount     343 non-null    float64
 17  Profit         343 non-null    float64
 18  Month          333 non-null    object
 19  Year           333 non-null    float64
 20  Weekday        333 non-null    object
dtypes: datetime64[ns](2), float64(7), object(12)
memory usage: 65.3+ KB

In [50]:
df.isnull().sum()

Order_ID           0
Order_Date        47
Customer_Name      0
Email              0
Phone              0
City               0
State              0
Product            0
Category           0
Qty                0
Unit_Price        37
Discount           0
Payment_Mode       0
Order_Status       0
Delivery_Date    245
Sales             37
Net_Amount        37
Profit            37
Month             47
Year              47
Weekday           47
dtype: int64

In [51]:
df.describe()

,Order_Date,Qty,Unit_Price,Discount,Delivery_Date,Sales,Net_Amount,Profit,Year
count,333,380.000000,343.000000,380.0,135,343.000000,343.000000,343.000000,333.0
mean,2025-04-02 17:35:08.108108032,3.328947,3252.352770,0.0,2025-06-16 16:42:40,11103.664723,11103.664723,2220.732945,2025.0
min,2025-01-01 00:00:00,1.000000,499.000000,0.0,2025-01-02 00:00:00,499.000000,499.000000,99.800000,2025.0
25%,2025-02-14 00:00:00,2.000000,999.000000,0.0,2025-03-07 00:00:00,2599.000000,2599.000000,519.800000,2025.0
50%,2025-04-05 00:00:00,3.000000,1999.000000,0.0,2025-07-03 00:00:00,5997.000000,5997.000000,1199.400000,2025.0
75%,2025-05-16 00:00:00,5.000000,4999.000000,0.0,2025-09-04 12:00:00,12995.000000,12995.000000,2599.000000,2025.0
max,2025-06-30 00:00:00,5.000000,9999.000000,0.0,2025-12-06 00:00:00,49995.000000,49995.000000,9999.000000,2025.0
std,NaN,1.458196,3026.092014,0.0,NaN,12194.528486,12194.528486,2438.905697,0.0

In [52]:
# Export Clean Data

df.to_csv('Clean_Ecommerce.csv',index=False)